/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [package_id]
      ,[project_version_lsn]
      ,[name]
      ,[package_guid]
      ,[description]
      ,[package_format_version]
      ,[version_major]
      ,[version_minor]
      ,[version_build]
      ,[version_comments]
      ,[version_guid]
      ,[project_id]
      ,[entry_point]
      ,[validation_status]
      ,[last_validation_time]
      ,[package_data]
  FROM [SSISDB].[internal].[packages]

  select distinct name from [SSISDB].[internal].[packages]